### ISSUE TITLE
Issues identified on May 28

### ISSUE THREAD

**Issue by gaurav-naik** [mntechnique/kisanmitra_erpnext#35]
### Development related (pending issues)
- [ ] Dashboard/Incoming calls
   - [ ] Create lead redirects to Lead form instead of Popup.
   - [ ] Call Description popup (second popup) showing for all users.
   - [ ] Failing features with zero-prefixed number:
      - [ ] Outgoing calls, linkages of communication to Issue.
      - [ ] Issue filtering
- [ ] SMS
   - [ ] Automatic Notification by SMS on Issue
- [ ] Caller name on Issue

### Ongoing Support related
- [ ] Visibility to government officials via Role Permissions
   - [ ] Explore in-built role and permissions for District/Mandal/Department based access.
- [ ] Dropbox setup
   - [ ] Credentials for Dropbox

### Additional Features
- [ ] KM Collector Review Report
   - [ ] Basic Report to show Issues filtered by Date/Department
   - [ ] Weekly report to officials. Data visibility based on Role Permissions allotted to govt officials
- [ ] Global Search:
   - [ ] Explore marking Issue's name as "In Global Search" and try searching.
- [ ] Document Versioning visibility to a few roles/ Switching visibility via front end
- [ ] SMS Alert Feature
   - [ ] When Assigned a Todo for Issue,similar to "notify by email" option,there should be "notify by sms"

**Comment by nanoharsha** [comment]
For issue mentioned above "Explore marking Issue's name as "In Global Search" and try searching", we see that from front end there is no way we can set the Case ID field as Global Search. Also by default the raised by(mobile number) is part of Global Search, but when we search by Mobile number, only contact or communication is visible. We can't see any issues data being seen when we search by mobile number. So not really sure how the global search works.

**Comment by gaurav-naik** [comment]
Created separate issues. Closing this now.
