### ISSUE TITLE
Navigating to Issue from Lead/Contact

### ISSUE THREAD

**Issue by nanoharsha** [mntechnique/kisanmitra_erpnext#5]
We are unable to view the linked issue from a Lead/Contact Page
But Navigating from Issue to Lead/contact is working fine.

**Comment by nanoharsha** [comment]
Issues encountered while testing:
1) Popup is showing on entire screen. Where as in Vtiger its shows on the top right corner.                                                                                                                             2) While receiving a popup if we click anywhere on the screen then the popup is vanishing.
3) Popup is showing for everyone. It has to show whoever is getting the call.

**Comment by gaurav-naik** [comment]
1. Potential pull request: "Popup behaviour in System Settings"
2. Need to look at the call flow again and re-position the Passthru app, or check the Popup URL feature of the connect app.

**Comment by saurabh-bhosale** [comment]
Closing this for now, since restricted popup display and closing of popup by random clicks is implemented and fixed in newer commits.
